/**
 * Stable, machine-readable error codes across LogicLab.
 * Clients must branch on these error codes rather than parsing localized strings.
 */

export const ERROR_CODES = {
  VALIDATION_ERROR: "VALIDATION_ERROR",
  UNAUTHORIZED: "UNAUTHORIZED",
  AUTH_REQUIRED: "AUTH_REQUIRED",
  AUTH_INVALID: "AUTH_INVALID",
  FORBIDDEN: "FORBIDDEN",
  NOT_FOUND: "NOT_FOUND",
  RESOURCE_NOT_FOUND: "RESOURCE_NOT_FOUND",
  OWNERSHIP_REQUIRED: "OWNERSHIP_REQUIRED",
  CONFLICT: "CONFLICT",
  DUPLICATE_RESOURCE: "DUPLICATE_RESOURCE",
  RATE_LIMIT_EXCEEDED: "RATE_LIMIT_EXCEEDED",
  EXECUTION_LIMIT_EXCEEDED: "EXECUTION_LIMIT_EXCEEDED",
  DATABASE_UNAVAILABLE: "DATABASE_UNAVAILABLE",
  DATABASE_ERROR: "DATABASE_ERROR",
  INTERNAL_ERROR: "INTERNAL_ERROR",
  EXTERNAL_SERVICE_ERROR: "EXTERNAL_SERVICE_ERROR",
  ALGORITHM_EXECUTION_ERROR: "ALGORITHM_EXECUTION_ERROR",
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
